
development:
  adapter: postgresql
  encoding: unicode
  database: splaty_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: splaty_test
  pool: 5
  username: splaty
  password:

